SET @ENTRY := 100601;
DELETE FROM creature_template WHERE entry IN (@ENTRY);
DELETE FROM locales_creature WHERE entry IN (@ENTRY);
DELETE FROM creature WHERE id IN (@ENTRY);

SET @STRING_ENTRY := 12000;
DELETE FROM `mangos_string` WHERE `entry` BETWEEN  @STRING_ENTRY AND @STRING_ENTRY+21;

SET @TEXT_ID := 50700;
DELETE FROM `npc_text` WHERE `ID` BETWEEN @TEXT_ID AND @TEXT_ID+1;
DELETE FROM `locales_npc_text` WHERE `entry` BETWEEN @TEXT_ID AND @TEXT_ID+1;