Attunement.Enable = 1
Attunement.DefaultRate = 1.0
Attunement.MinRate = 0.1
Attunement.MaxRate = 100
Attunement.Aura.Tier1.SpellId = 0
Attunement.Aura.Tier2.SpellId = 0
Attunement.Aura.Tier3.SpellId = 0
Attunement.Aura.Tier4.SpellId = 0
Attunement.Aura.Tier5.SpellId = 0
