-- VIP master spell: cleanup migration.
--
-- HISTORY:
--   v1: tried INSERT of custom spell 91200 "Wayfarer's Boon" — failed at
--       runtime because vanilla 1.12 clients only know spell IDs from
--       their bundled Spell.dbc, so a server-only ID 91200 couldn't be
--       cast or displayed by the client.
--   v2: hot-fixed to use vanilla spell 22888 "Rallying Cry of the
--       Dragonslayer" — worked but conflicted (it's also one of the
--       bundle spells).
--   v3 (current): use vanilla spell 18282 "Dummy Spell" — already
--       Effect1=SPELL_EFFECT_DUMMY in vanilla spell_template, exists
--       in client Spell.dbc, zero references in item/trainer/chain
--       tables. No spell_template change needed; VipModule::OnCast
--       hooks the cast and fires the cascade.
--
-- This file just does the v1 cleanup (the obsolete custom row). The
-- master-spell behavior comes from the vanilla 18282 row + the OnCast
-- hook in the VipModule.
--
-- Idempotent.

DELETE FROM `spell_template` WHERE `Id` = 91200;
